name: walletium
description: Virtual crypto wallet.

publish_to: "none"

version: 1.2.0+2

environment:
  sdk: ">=3.5.0 <4.2.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  get: 4.6.6

  flutter_screenutil: 5.9.3
  font_awesome_flutter: ^10.8.0
  image: ^3.0.1
  image_picker: 1.1.2
  carousel_slider: 5.0.0
  pin_code_fields: 8.0.1
  loading_animation_widget: ^1.3.0

  #  for backend
  get_storage: ^2.1.1
  logger: ^2.5.0
  qr_flutter: ^4.1.0
  dotted_border: 2.1.0
  dotted_decoration: ^2.0.0
  share_plus: ^10.1.2
  cached_network_image: 3.4.1
  connectivity_plus: 5.0.2
  flutter_spinkit: 5.2.1
  dropdown_button2: ^2.3.9
  toggle_switch: 2.3.0
  delayed_display: ^2.0.0
  flutter_svg:
  file_picker: ^8.1.4
  flutter_inappwebview: ^6.1.5
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.20.1
  lottie: ^3.1.3

  dynamic_languages:
    git:
      url: https://github.com/appdevsx/dynamic_languages
      ref: main
  win32: ^5.5.4
  rename_app: ^1.6.1

  restart_app: ^1.3.2
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.0.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  google_fonts: ^6.2.1
  flip_card: ^0.7.0

dev_dependencies:
  flutter_launcher_icons:
  change_app_package_name: ^1.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/deep_link/apple-app-site-association
    - assets/empty_animation.json
    - assets/font/
    - assets/images/
    - assets/images/bg/
    - assets/images/bg/drawer_bg.svg
    - assets/images/bg/sign-in-bg.svg
    - assets/images/others/
    - assets/images/others/confirm.svg
    - assets/images/others/congratulations.svg
    - assets/images/others/forgot-password.svg
    - assets/images/splash/
    - assets/svg/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/font/Roboto-Bold.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
    - family: Monserrat
      fonts:
        - asset: assets/font/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/font/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Montserrat/Montserrat-Black.ttf
          weight: 900
 # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick